# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{neverblock}
  s.version = "0.1.6.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Muhammad A. Ali", "Ahmed Sobhi", "Osama Brekaa", "Nicholas Silva"]
  s.date = %q{2010-02-03}
  s.description = %q{NeverBlock is a collection of classes and modules that help you write evented non-blocking applications in a seemingly blocking mannner.}
  s.email = %q{conickal@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "Rakefile",
     "VERSION",
     "lib/active_record/connection_adapters/neverblock_mysql_adapter.rb",
     "lib/active_record/connection_adapters/neverblock_postgresql_adapter.rb",
     "lib/never_block.rb",
     "lib/never_block/db/fibered_db_connection.rb",
     "lib/never_block/db/fibered_mysql_connection.rb",
     "lib/never_block/db/fibered_postgres_connection.rb",
     "lib/never_block/db/pooled_db_connection.rb",
     "lib/never_block/extensions/fiber_extensions.rb",
     "lib/never_block/frameworks/activerecord.rb",
     "lib/never_block/frameworks/rails.rb",
     "lib/never_block/pool/fiber_pool.rb",
     "lib/never_block/pool/fibered_connection_pool.rb",
     "lib/never_block/servers/mongrel.rb",
     "lib/never_block/servers/thin.rb",
     "lib/neverblock-mysql.rb",
     "lib/neverblock-pg.rb",
     "lib/neverblock.rb",
     "neverblock.gemspec",
     "spec/fiber_extensions_spec.rb",
     "spec/fiber_pool_spec.rb",
     "spec/fibered_connection_pool_spec.rb",
     "tasks/spec.rake",
     "test/test_mysql.rb",
     "test/test_pg.rb"
  ]
  s.homepage = %q{http://github.com/conickal/neverblock}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Utilities for non-blocking stack components}
  s.test_files = [
    "spec/fiber_extensions_spec.rb",
     "spec/fiber_pool_spec.rb",
     "spec/fibered_connection_pool_spec.rb",
     "test/test_mysql.rb",
     "test/test_pg.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12.2"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0.12.2"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0.12.2"])
  end
end

